/******* Do not edit this file *******
Simple Custom CSS and JS - by Silkypress.com
Saved: Dec 02 2023 | 07:07:47 */
const btnNavLink = document.querySelector("#btn-nav-link");
const containerNavIndex = document.querySelector("#container-nav");

btnNavLink.addEventListener("click", () => {
  if (containerNavIndex.classList.contains("bg-container-nav")) {
    containerNavIndex.classList.remove("bg-container-nav");
  } else {
    containerNavIndex.classList.add("bg-container-nav");
  }
});

